exports.NAV = ["Défi 1","Défi 2","Défi 3","Bonus"];

exports.TOOLBOX = [
    { id: '1', label: 'IntelliJ', language:["java"],description:'IntelliJ IDEA est un IDE Java commercial développé par JetBrains. Il est fréquemment appelé par le simple nom d’« IntelliJ », « IDEA » ou « IDJ ».', ref:[{title:'install',link:'https://www.jetbrains.com/idea/'}]},
    { id: '2', label: 'Java', language:["java"],description:'Java est un langage de programmation orienté objet créé par James Gosling et Patrick Naughton, employés de Sun Microsystems, avec le soutien de Bill Joy (cofondateur de Sun Microsystems en 1982), présenté officiellement le 23 mai 1995 au SunWorld.', ref:[{title:'install',link:'http://www.oracle.com/technetwork/java/javase/downloads/index.html'}]},
    { id: '4', label: 'Atom', language:["javascript"],description:'Atom est un éditeur de texte libre pour macOS, GNU/Linux et Windows développé par GitHub. Il supporte des plug-ins écrits en Node.js et implémente Git Control. La plupart des extensions sont sous licence libre et sont maintenues par la communauté6. Atom est basé sur Chromium et Electron, et est écrit en CoffeeScript7. Il est aussi utilisé en tant qu’IDE.', ref:[{title:'install',link:'https://atom.io/'},{title:'addons',link:'https://www.sitepoint.com/10-essential-atom-add-ons/'}]},
    { id: '5', label: 'Node', language:["javascript"],description:'Node.js est une plateforme logicielle libre et événementielle en JavaScript orientée vers les applications réseau qui doivent pouvoir monter en charge.', ref:[{title:'install',link:'https://nodejs.org'}]},
    { id: '6', label: 'Docker', language:["java","javascript"],description:'Docker est un logiciel libre qui automatise le déploiement d\'applications dans des conteneurs logiciels5. Selon la firme de recherche sur l\'industrie 451 Research, « Docker est un outil qui peut empaqueter une application et ses dépendances dans un conteneur isolé, qui pourra être exécuté sur n\'importe quel serveur ». Ceci permet d\'étendre la flexibilité et la portabilité d’exécution d\'une application, que ce soit sur la machine locale, un cloud privé ou public, une machine nue, etc.6.', ref:[{title:'install',link:'https://www.docker.com/'}]},
    { id: '7', label: 'Git', language:["java","javascript"],description:'Git est un logiciel de gestion de versions décentralisé. C\'est un logiciel libre créé par Linus Torvalds, auteur du noyau Linux, et distribué selon les termes de la licence publique générale GNU version 2. En 2016, il s\'agit du logiciel de gestion de versions le plus populaire qui est utilisé par plus de douze millions de personnes.', ref:[{title:'install',link:'https://git-scm.com/'},{title:'addons',link:'https://danielkummer.github.io/git-flow-cheatsheet/'}]},
    { id: '8', label: 'Visual Studio Code', language:["javascript"],description:'Visual Studio Code est un éditeur de code extensible développé par Microsoft', ref:[{title:'install',link:'https://code.visualstudio.com/'}]}
];

exports.BDD = [
    { id: '1', label: 'MongoDb', bdd:"nosql", language:["java","javascript"],description:'MongoDB est un système de gestion de base de données orientée documents, répartissable sur un nombre quelconque d\'ordinateurs et ne nécessitant pas de schéma prédéfini des données. Il est écrit en C++. Le serveur et les outils sont distribués sous licence AGPL, les pilotes sous licence Apache et la documentation sous licence Creative Commons2. Il fait partie de la mouvance NoSQL.', ref:[{title:'install',link:'https://www.mongodb.com/'}]}
];

exports.WHY_STACK = [
    { id: '1', label: 'IntelliJ', description:'Every time I visit a Java conference or a meetup and talk to people unfamiliar with IntelliJ IDEA, I get similar questions again and again: “What’s so special about IntelliJ IDEA? What does IntelliJ IDEA has that other Java IDEs don’t?” In response I usually simply demo a few of its features and then just watch their jaws dropping...', ref:[{title:'link',link:'https://blog.jetbrains.com/idea/2016/03/enjoying-java-and-being-more-productive-with-intellij-idea/'},{title:'keymap',link:'https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf'}]},
    { id: '2', label: 'Kotlin', description:'Why Kotlin is my next programming language...', ref:[{title:'link',link:'https://medium.com/@octskyward/why-kotlin-is-my-next-programming-language-c25c001e26e3'}]},
    { id: '3', label: 'Atom', description:'There are a lot of text editors out there; why should you spend your time learning about and using Atom...', ref:[{title:'link',link:'https://flight-manual.atom.io/getting-started/sections/why-atom/'}]},
    { id: '4', label: 'Springboot', description:'Spring Boot aims to make it easy to create Spring-powered, production-grade applications and services with minimum fuss. It takes an opinionated view of the Spring platform so that new and existing users can quickly get to the bits they need...', ref:[{title:'link',link:'https://spring.io/blog/2013/08/06/spring-boot-simplifying-spring-for-everyone'}, {title:'13..10 reasons why?..',link:'http://blog.ellixo.com/2015/06/08/10-raisons-de-se-mettre-a-Spring-Boot-1ere-partie.html'}]},
    { id: '5', label: 'Node', description:'Aujourd\'hui, JavaScript est de retour et il prend sa revanche. En quelque sorte, les développeurs sont en train de découvrir que ce langage qu\'ils ont longtemps ignoré, parfois même méprisé, cache en fait bien son jeu...', ref:[{title:'link',link:'https://openclassrooms.com/fr/courses/1056721-des-applications-ultra-rapides-avec-node-js/1056866-node-js-mais-a-quoi-ca-sert'}]},
    { id: '6', label: 'Docker', description:'Docker, voilà un mot qui revient souvent sur le web quand on est développeur et que l’on fait de la veille technologique...', ref:[{title:'link',link:'https://apprendre-la-programmation.net/docker-for-developers/'}]},
    { id: '7', label: 'Git', description:'Why I don’t like IBM RTC as Source Control Management..', ref:[{title:'link',link:'https://romixch.wordpress.com/2015/03/10/why-i-dont-like-ibm-rtc-as-source-control-management/'}]},
    { id: '8', label: 'DockerFile', description:'Docker can build images automatically by reading the instructions from a Dockerfile. A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image. Using docker build users can create an automated build that executes several command-line instructions in succession.', ref:[{title:'link',link:'https://docs.docker.com/engine/reference/builder/#usage'}]},
    { id: '9', label: 'Express', description:'Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.', ref:[{title:'link',link:'https://expressjs.com/'}]},
    { id: '10', label: 'Postgresql', description:'PostgreSQL comes with many features aimed to help developers build applications, administrators to protect data integrity and build fault-tolerant environments, and help you manage your data no matter how big or small the dataset. In addition to being free and open source, PostgreSQL is highly extensible. For example, you can define your own data types, build out custom functions, even write code from different programming languages without recompiling your database!', ref:[{title:'link',link:'https://www.postgresql.org/about/'},{title:'PostgreSql vs Mysql',link:'https://openclassrooms.com/fr/courses/1121356-mysql-et-postgresql-lequel-choisir'}]},
    { id: '11', label: 'MongoDb', description:'Avec l’explosion des volumes de données à traité plusieurs solutions ont vu le jour. Les bases de données non relationnelles ont permis ainsi de répondre à ces demandes en matière de gestion de base de données. Mongodb fait partie de ces base de données non relationnel et est utilisé par de nouvelles applications afin d’augmenter ou remplacer l’infrastructure relationnelle existante', ref:[{title:'MongoDB vs Mysql',link:'https://www.supinfo.com/articles/single/4921-comparaison-mysql-mongodb'}]},
    { id: '12', label: 'React', description:'React (aussi appelé React.js ou ReactJS) est une bibliothèque JavaScript libre développée par Facebook depuis 2013. Le but principal de cette bibliothèque est de faciliter la création d\'application web monopage, via la création de composants dépendant d\'un état et générant une page (ou portion) HTML à chaque changement d\'état.', ref:[{title:'link',link:'https://reactjs.org/'}]}
];

exports.CHEAT_SHEET=[
    { id: '1', label: 'Git cheat sheet', tech:'Git', description:'Use this handy Git cheat sheet guide to enhance your workflow. This Git cheat sheet saves you time when you just can\'t remember what a command is or don\'t want to use git help in the command line. It is hard to memorize all the important Git commands by heart, so print this out or save it to your desktop to resort to when you get stuck. We’ve included the basic Git commands to help you learn Git, and more advanced concepts around Git branches, remote repositories, undoing changes, and more.', ref:[{title:'link',link:'https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet'}]},
    { id: '2', label: 'Docker cheat sheet', tech:'Docker', description:'Use this handy Docker cheat sheet guide to enhance your workflow.', ref:[{title:'link',link:'https://devhints.io/docker'}]}
];

exports.JAVA_STACK = [
    { id: '1', project: 'Backend', key: 'Backend', bdd:'none', tech:['springboot'],label:'Building a RESTful Web Service with Springboot', description:'Start with this project and complete it with your class. This project walks you through the process of creating a "hello world" RESTful web service with Spring.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/java-backend'}]},
    { id: '2', project: 'Backend', key: 'Backend',bdd:'nosql', tech:['springboot','dockerfile','mongodb'], label:'Building a RESTful Web Service with Springboot and MongoDb', description:'Start with this project and complete it with your class. This project walks you through the process of creating a "hello world" RESTful web service with Spring and MongoDb.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/java-backend-bdd.git'},{title:'guide',link:'https://spring.io/guides/gs/accessing-data-mongodb/'}]},
    { id: '3', project: 'Website', key: 'web',bdd:'none', tech:['springboot','dockerfile'], label:'Serving Web Content with Spring MVC and Templating HTML', description:'This guide walks you through the process of creating a "hello world" web site with Spring.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/java-website.git'}]},
    { id: '4', project: 'Website with no sql database',key: 'web', bdd:'nosql', tech:['springboot','dockerfile','mongodb'], label:'Serving Web Content with Spring MVC with no sql database', description:'Start with these guides and complete it with your class. This guide walks you through the process of creating a website with Spring and nosql database.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/java-website-bdd.git'}]},
    { id: '5', project: 'React website', key: 'react', bdd:'none', tech:['springboot','dockerfile','react'], label:'Serving React Web Content and java backend', description:'Start with these projects and complete it with your class. This guide walks you through the process of creating a "hello world"  web service with React and Java.', ref:[{title:'front',link:'https://gitlab.com/innostarterkit/javascript-react-website-bdd.git'}]},
    { id: '6', project: 'React website with no sql database', key: 'react', bdd:'nosql', tech:['springboot','dockerfile','react','mongodb'], label:'Serving React Web Content, java backend and MongoDb', description:'Start with these projects and complete it with your class. This guide walks you through the process of creating a "hello world"  web service with Node.', ref:[{title:'front',link:'https://gitlab.com/innostarterkit/javascript-react-website-bdd.git'},{title:'back',link:'https://gitlab.com/innostarterkit/java-backend-bdd.git'}]}
];

exports.JAVASCRIPT_STACK = [
    { id: '1', project: 'Backend', key: 'Backend', bdd:'none', tech:['node','express','dockerfile'],label:'Create a RESTful Web Service with Node.js', description:'Start with this project and complete it with your class. This guide walks you through the process of creating a "hello world" RESTful web service with Node.js.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/javascript-backend.git'}]},
    { id: '2', project: 'Backend', key: 'Backend', bdd:'nosql', tech:['node','express','dockerfile','mongodb'], label:'Create a RESTful Web Service with Node.js and MongoDb', description:'Start with this guide and complete it with your class. This guide walks you through the process of creating a "hello world" RESTful web service with Node.js and MongoDb.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/javascript-backend-bdd.git'}]},
    { id: '3', project: 'Website', key: 'web', bdd:'none', tech:['node','express','dockerfile'], label:'Serving Web Content with Node and Templating HTML', description:'Start with this project and complete it with your class. This guide walks you through the process of creating a "hello world" web service with Node.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/javascript-website-bdd.git'}]},
    { id: '4', project: 'Website with nosql database', key: 'web', bdd:'nosql', tech:['node','express','dockerfile','mongodb'], label:'Serving Web Content with Node, Templating Html and nosql database', description:'Start with this guide and complete it with your class. This guide walks you through the process of creating a "hello world" RESTful web service with Node, Templating Html and nosql database.', ref:[{title:'package',link:'https://gitlab.com/innostarterkit/javascript-website-bdd.git'}]},
    { id: '5', project: 'React website', key: 'react', bdd:'none', tech:['node','dockerfile','react'], label:'Serving React Web Content', description:'Start with these projects and complete it with your class. This guide walks you through the process of creating a "hello world"  web service with React.', ref:[{title:'front',link:'https://gitlab.com/innostarterkit/javascript-react-website-bdd.git'}]},
    { id: '6', project: 'React website with no sql database', key: 'react', bdd:'nosql', tech:['node','dockerfile','react','mongodb'], label:'Serving React Web Content, Node backend and MongoDb', description:'Start with these projects and complete it with your class. This guide walks you through the process of creating a "hello world"  web service with React, Node and MongoDb.', ref:[{title:'front',link:'https://gitlab.com/innostarterkit/javascript-react-website-bdd.git'},{title:'back',link:'https://gitlab.com/innostarterkit/java-backend-bdd.git'}]}
];

exports.KOTLIN_STACK = [
    { id: '1', project: 'Backend', key: 'Backend', bdd:'none', tech:['springboot','dockerfile'],label:'Building a RESTful Web Service with Springboot', description:'This tutorial walks us through the process of creating a simple REST controller with Spring Boot Kotlin works quite smoothly with Spring Boot and many of the steps found on the Spring Guides for creating a RESTful service can be followed verbatim for Kotlin. There are some minor differences however when it comes to defining the Gradle configuration and the project layout structure, as well as the initialization code.', ref:[{title:'guide',link:'https://kotlinlang.org/docs/tutorials/spring-boot-restful.html'}]},
    { id: '2', project: 'Backend', key: 'Backend', bdd:'sql', tech:['springboot','dockerfile','postgresql'], label:'Building a RESTful Web Service with Springboot', description:'Start with this guide and complete it with your class. This guide walks you through the process of creating a "hello world" RESTful web service with Spring.', ref:[{title:'guide',link:'https://kotlinlang.org/docs/tutorials/spring-boot-restful.html'},{title:'configuring springboot for postgresql',link:'https://springframework.guru/configuring-spring-boot-for-postgresql/'}]},
    { id: '3', project: 'Backend', key: 'Backend', bdd:'nosql', tech:['springboot','dockerfile','mongodb'], label:'Building a RESTful Web Service with Springboot', description:'Start with this guide and complete it with your class. This guide walks you through the process of creating a "hello world" RESTful web service with Spring.', ref:[{title:'guide',link:'https://kotlinlang.org/docs/tutorials/spring-boot-restful.html'},{title:'accessing data with MongoDB',link:'https://spring.io/guides/gs/accessing-data-mongodb/'}]},
    { id: '4', project: 'Website', key: 'web', bdd:'none', tech:['springboot','dockerfile','postgresql'], label:'Serving Web Content with Spring MVC', description:'Start with this guide and complete it with your class. This guide walks you through the process of creating a "hello world" RESTful web service with Spring.', ref:[{title:'guide',link:'https://spring.io/guides/tutorials/spring-boot-kotlin/'}]},
    { id: '6', project: 'Website with nosql database', key: 'web', bdd:'nosql', tech:['springboot','dockerfile','mongodb'], label:'Serving Web Content with Spring MVC with nosql database', description:'Start with this project and complete it with your class. This guide walks you through the process of creating a "hello world"  web service with Node.', ref:[{title:'guide',link:'https://gitlab.com/innostarterkit/javascript-backend-bdd.git'},{title:'accessing data with MongoDB',link:'https://spring.io/guides/gs/accessing-data-mongodb/'}]},
    { id: '6', project: 'React website', key: 'react', bdd:'none', tech:['springboot','dockerfile','mongodb','react'], label:'Serving Web Content with Spring MVC with nosql database', description:'Start with this project and complete it with your class. This guide walks you through the process of creating a "hello world"  web service with Node.', ref:[{title:'guide',link:'https://gitlab.com/innostarterkit/javascript-backend-bdd.git'},{title:'accessing data with MongoDB',link:'https://spring.io/guides/gs/accessing-data-mongodb/'}]}
];

exports.DOCKER_FILE = [
    { id: '1', project: 'Backend', language:'java', bdd:'none',label:'Complete your project with DockerFile', description:'Follow the previous guide and add this file on your base path. (next to pom.xml ;) )', ref:[{title:'file',link:'https://spring.io/guides/gs/rest-service/'}]},
    { id: '2', project: 'Backend', language:'javascript', bdd:'none',label:'Complete your project with DockerFile', description:'Follow the previous guide and add this file on your base path. (next to package.json ;) )', ref:[{title:'file',link:'https://spring.io/guides/gs/rest-service/'}]},
    { id: '3', project: 'Backend', language:'kotlin', bdd:'none',label:'Complete your project with DockerFile', description:'Follow the previous guide and add this file on your base path. (next to pom.xml ;) )', ref:[{title:'file',link:'https://spring.io/guides/gs/rest-service/'}]}
];

exports.PUSH = [
    { id: '1',label:'Push on Gitlab or Github', ref: [{title:'1',cmd:'For Deploying, you need to push your project on Gitlab or Github'},{title:'2',cmd:'Don\'t forget to remove the old .git !!!'}]},
    { id: '2',label:'Git global setup', ref: [{title:'1',cmd:'git config --global user.name "user name"'},{title:'2',cmd:'git config --global user.email "mail@pole-emploi.fr"'}]},
    { id: '3',label:'Create a new repository', ref: [{title:'1',cmd:'git clone https://gitlab.com/innostarterkit/xxx.git'},{title:'2',cmd:'cd projects'},{title:'3',cmd:'touch README.md'},{title:'4',cmd:'git add README.md'},{title:'5',cmd:'git commit -m "add README"'},{title:'6',cmd:'git push -u origin master'}]},
    { id: '4',label:'Existing folder', ref: [{title:'1',cmd:'cd existing_folder'},{title:'2',cmd:'git init'},{title:'3',cmd:'git remote add origin https://gitlab.com/innostarterkit/test.git'},{title:'4',cmd:'git add .'},{title:'5',cmd:'git commit -m "Initial commit"'},{title:'6',cmd:'git push -u origin master'}]},
    { id: '5',label:'Existing Git repository', ref: [{title:'1',cmd:'cd existing_repo'},{title:'2',cmd:'git remote rename origin old-origin'},{title:'3',cmd:'git remote add origin https://gitlab.com/innostarterkit/test.git'},{title:'4',cmd:'git push -u origin --all'},{title:'5',cmd:'git push -u origin --tags'}]}
];

exports.EXPOSE = [
    { id: '1', label: 'Build and Expose package',description:'This job allow you to build and expose your package. You need to fill your git url, version, port and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Build%20and%20Expose%20package/'}]},
    { id: '2', label: 'Update and Expose package',description:'This job allow you to update and expose your package. You need to fill your git url, version and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Update%20and%20Expose%20package/'}]},
];


exports.SCRATCH = [
    { id: '1', label: 'Dessiner une croix',description:'reproduire l’animation ci dessus', ref:[{title:'télécharger arrière plan',link:'https://medium.com/@vdngaite/d%C3%A9fi-1-la-croix-e0a71b18b4fc'}]},
    { id: '2', label: 'Space war',description:'This job allow you to update and expose your package. You need to fill your git url, version and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Update%20and%20Expose%20package/'}]},
    { id: '3', label: 'Tetris',description:'This job allow you to update and expose your package. You need to fill your git url, version and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Update%20and%20Expose%20package/'}]},
];

exports.TWINE = [
    { id: '1', label: 'Build and Expose package',description:'This job allow you to build and expose your package. You need to fill your git url, version, port and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Build%20and%20Expose%20package/'}]},
    { id: '2', label: 'Update and Expose package',description:'This job allow you to update and expose your package. You need to fill your git url, version and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Update%20and%20Expose%20package/'}]},
];

exports.PROCESSING = [
    { id: '1', label: 'Build and Expose package',description:'This job allow you to build and expose your package. You need to fill your git url, version, port and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Build%20and%20Expose%20package/'}]},
    { id: '2', label: 'Update and Expose package',description:'This job allow you to update and expose your package. You need to fill your git url, version and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Update%20and%20Expose%20package/'}]},
];

exports.CHATBOT = [
    { id: '1', label: 'Build and Expose package',description:'This job allow you to build and expose your package. You need to fill your git url, version, port and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Build%20and%20Expose%20package/'}]},
    { id: '2', label: 'Update and Expose package',description:'This job allow you to update and expose your package. You need to fill your git url, version and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Update%20and%20Expose%20package/'}]},
];

exports.JAVASCRIPT = [
    { id: '1', label: 'Build and Expose package',description:'This job allow you to build and expose your package. You need to fill your git url, version, port and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Build%20and%20Expose%20package/'}]},
    { id: '2', label: 'Update and Expose package',description:'This job allow you to update and expose your package. You need to fill your git url, version and mail before execute it', ref:[{title:'link',link:'http://159.122.183.120:30656/job/InnoStarterKit%20-%20Update%20and%20Expose%20package/'}]},
];